### ISSUE TITLE
Manual thumbnails for uploads via the website

### ISSUE THREAD

**Issue by andybak** [icosa-foundation/icosa-gallery#10]
You can add a thumbnail to an existing upload. Would be nice to be able to do it on initial upload too. Maybe just the presence of a file called "thumbnail.png" in the zip or separate? 

(maybe that already works - i haven't tried. But if it does then the text needs to explain that on the upload page)

**Comment by jamesrampton** [comment]
This was already possible via the zip file. I've updated the text on the uploads view to reflect this.
