### ISSUE TITLE
Asset lister url params

### ISSUE THREAD

**Issue by andybak** [icosa-foundation/icosa-gallery#17]
We need to support:

format (BLOCKS, FBX, GLTF, GLTF2, TILT)

keywords (tags?)

category:

          animals
          architecture
          art
          food
          nature
          objects
          people
          scenes
          tech
          transport

curated (bool)

max_complexity (SIMPLE, MEDIUM, COMPLEX)

order_by (BEST, NEWEST, OLDEST, LIKED_TIME)

visibility (PRIVATE, PUBLISHED)

...on all asset endpoints (user, my etc)

**Comment by jamesrampton** [comment]
I believe this is done.
