### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by andybak** [icosa-foundation/icosa-gallery#23]
These are baked in categories in the Poly API

      {PolyCategory.ANIMALS, "animals"},
      {PolyCategory.ARCHITECTURE, "architecture"},
      {PolyCategory.ART, "art"},
      {PolyCategory.FOOD, "food"},
      {PolyCategory.NATURE, "nature"},
      {PolyCategory.OBJECTS, "objects"},
      {PolyCategory.PEOPLE, "people"},
      {PolyCategory.PLACES, "scenes"},
      {PolyCategory.TECH, "tech"},
      {PolyCategory.TRANSPORT, "transport"}

They appear to match with tags but we need to probably "bless" them in some way as distinct from arbitrary user tags. Note that "PLACES" maps to "scenes" whereas all the others are a simple case-insensitive match.

**Comment by jamesrampton** [comment]
Done, I've made some assumptions: https://github.com/icosa-foundation/icosa-gallery/commit/550a3b53ba6e6bf1708e548bc037083feb45664d#diff-53db70c59eb017b625c2ffeb7f2e8c80ec458a3bdcb957c50609fe749e59f194R270

**Comment by andybak** [comment]
Lower case is more likely but probably do case insensitive
