### ISSUE TITLE
Should we omit optional fields if their value is null?

### ISSUE THREAD

**Issue by andybak** [icosa-foundation/icosa-gallery#25]

**Comment by jamesrampton** [comment]
I believe poly did this. I specifically remember orientingRotation having only the `w` field for most results. I'll look into this.

**Comment by jamesrampton** [comment]
That was quicker than I thought...

I've implemented this for /api/v1/assets only right now.

I've elected to also exclude fields which have a default value, so `"tags": []` is also omitted.

If you like that, I'll put this on the other routes including detail routes.

**Comment by jamesrampton** [comment]
This is now also on the detail view
