### ISSUE TITLE
"my liked" should include "public + liked" "private/unlisted but mine + liked"

### ISSUE THREAD

**Issue by andybak** [icosa-foundation/icosa-gallery#28]
Haven't checked if this is or isn't the case currently but it just occurred to me.

Also - should "unlisted" count as "public" if liked? I send you a link to my asset and you "like" it. Should you have access to it in your "liked" listers?

**Comment by jamesrampton** [comment]
> I send you a link to my asset and you "like" it. Should you have access to it in your "liked" listers?

This makes sense to me.

In the case of liked assets that are mine (and indeed anywhere on the site where I'm not looking at only my assets) should we have a visual indication that the asset is mine?

**Comment by jamesrampton** [comment]
Your initial question is done @andybak.

> In the case of liked assets that are mine (and indeed anywhere on the site where I'm not looking at only my assets) should we have a visual indication that the asset is mine, beyond user name alone?

Let me know if this is required.
