### ISSUE TITLE
admin badness

### ISSUE THREAD

**Issue by andybak** [icosa-foundation/icosa-gallery#29]
Very slow to load any user with several likes.

In general we should avoid any Django select widget if the queryset it constructs is huge. 

And even more so if it's an inline where they might be multiple of them.

(and double more so if we ever use list_editable ! )

We've solved this for our client projects. Django Autocomplete Light?

**Comment by jamesrampton** [comment]
I see you've already set `raw_id` on this field, which was going to be my sticking plaster for the moment.

Django 5x support is not officially mentioned for DAL, but I'll take a look.
