### ISSUE TITLE
Device code url

### ISSUE THREAD

**Issue by andybak** [icosa-foundation/icosa-gallery#31]
Please change to /device

The shorter the better for situations where someone has to type it in VR or on other devices where typing is clunky. (plus this is the previous url so I won't need to change things on my end)

**Comment by jamesrampton** [comment]
This is done. I had to set `APPEND_SLASH` to `False`, which means that all other urls are like the original icosa.gallery urls without a slash.

If you want trailing slashes to be removed instead of Django's behavior of `404`ing, I'll look at some middleware to handle this.
