### ISSUE TITLE
API - Filter assets by license type

### ISSUE THREAD

**Issue by jamesrampton** [icosa-foundation/icosa-gallery#32]
Need to get a handle on what the variants are. In theory, it could be any text, so we might need to restrict this to an enum.

Then the question is what should the variants be?

**Comment by mikeskydev** [comment]
I think this will mainly be based on the ones listed here: https://creativecommons.org/share-your-work/cclicenses/, plus an "all rights reserved"

**Comment by jamesrampton** [comment]
Thanks @mikeskydev.

Going to close this in favour of #34
