### ISSUE TITLE
Default sorting

### ISSUE THREAD

**Issue by andybak** [icosa-foundation/icosa-gallery#41]
From Google's API docs:

> BEST, NEWEST, OLDEST. Defaults to BEST, which ranks assets based on a combination of popularity and other features. 

We're going to have decent data for likes and downloads once we ingest all the available metadata. Newness should be a factor as well probably.

Something like: 

`ranking = (Likes * w1) + (Downloads * w2) + ((1 / (current_time - created_time)) * w3)`

And we can tweak the 3 weights until it looks ok. 

I *think* this is possible via the ORM. Something along the lines of:

```
Asset.objects.annotate(
    freshness=ExpressionWrapper(
        1 / (timezone.now() - F('created')),
        output_field=fields.FloatField()
    ),
    score=F('likes') * w1 + F('downloads') * w2 + F('freshness') * w3).order_by('-score')
```

Totally untested. It would be handy to keep this dynamic initially so we can fiddle with the weightings. And then maybe bake it in during save()

**Comment by andybak** [comment]
Also see #33

**Comment by andybak** [comment]
as @jamesrampton pointed out - I'm conflating downloads and views. We have both. Although "downloads" is not present in historical poly data.

**Comment by jamesrampton** [comment]
This ranking has been implemented. Let's discuss the weights when we're both next in a "room" together.
