### ISSUE TITLE
empty page token gives a 422

### ISSUE THREAD

**Issue by andybak** [icosa-foundation/icosa-gallery#43]
/v1/assets?pageToken=&keywords=

**Comment by andybak** [comment]
If we want to make it more likely that old Poly clients work with Icosa without tons of debugging, we should fix this.

**Comment by jamesrampton** [comment]
This is done. It required parsing the pageSize and pageToken params as str first, then int and falling back to the default if the value could not be parsed as an int.

Not the nicest, but it works.
