### ISSUE TITLE
Sidebar tweaks

### ISSUE THREAD

**Issue by andybak** [icosa-foundation/icosa-gallery#70]
1. Move "Support us" lower down
2. Huge "open brush" logo could be just another icon - along with blocks
3. More categories?
4. Maybe consider tightening up the use of space generally. Headings are big and some might be redundant. Could search be an icon that expands? Does it even belong in the sidebar (I'd generally expect it to be top right)

**Comment by mikeskydev** [comment]
The sidebar links are all invalid:
Twitter: https://twitter.com/icosafoundation
Discord: https://discord.gg/W7NCEYnEfy
GitHub: https://github.com/icosa-foundation

**Comment by mikeskydev** [comment]
Perhaps OpenCollective?

**Comment by jamesrampton** [comment]
@mikeskydev thanks; I've fixed the socials. @andybak I've used both the large open[blocks|brush] logos side by side. Still want just the icons?

Also those logos link to their landing pages which in turn link to their respective sites now.

**Comment by andybak** [comment]
Nope. That's fine. Can you take of target="_blank" for both of those?

Shall we keep this ticket open to track the landing page changes for blocks/brush or do you want to create a new one?

**Comment by jamesrampton** [comment]
> Can you take of target="_blank" for both of those?

Oops! This is done...

> Shall we keep this ticket open to track the landing page changes for blocks/brush or do you want to create a new one?

See #104 

> Move "Support us" lower down

Done.
