### ISSUE TITLE
Add a privacy policy, GDPR cookie banner and any other related formalities

### ISSUE THREAD

**Issue by andybak** [icosa-foundation/icosa-gallery#71]
As usual we'll have to think about how to make these configurable but that isn't necessary immediately.

**Comment by jamesrampton** [comment]
I've added a placeholder privacy policy at `/privacy-policy` but we will need some text. I'm never sure what goes into a privacy policy that's not already covered in `/terms`.

I've added both as links in the footer for now until we decide if we need both.

We don't use cookies other than for essential functionality so I think we don't need to worry about a GDPR banner.

**Comment by jamesrampton** [comment]
Added most of the applicible text from openbrush.app's privacy policy where it makes sense for us.
