### ISSUE TITLE
/poly to load content due to a 500 error against api.icosa.gallery/poly/assets

### ISSUE THREAD

**Issue by Utopiah** [icosa-foundation/icosa-gallery#74]
Hi, trying to reach https://icosa.gallery/poly the page loads but no content is being displayed.

There is no error in the console but in the network console https://api.icosa.gallery/poly/assets?results=24&page=0 gets an error 500 and there is an "CORS Missing Allow Origin" error.

**Comment by andybak** [comment]
Hi,

The instance running on https://icosa.gallery/ is very old and predates the recent rewrite. We'll have a public instance up soon.
