### ISSUE TITLE
Open Brush logo in sidebar

### ISSUE THREAD

**Issue by andybak** [icosa-foundation/icosa-gallery#85]
1. Can it be smaller?
2. Do we want to add Blocks as well?

**Comment by mikeskydev** [comment]
I note it's the non-stroke version without the space between open and brush

**Comment by andybak** [comment]
![Logo](https://github.com/user-attachments/assets/be29dd50-3718-45c2-b8ac-75066d4c05b7)

![library_logo_transparent](https://github.com/user-attachments/assets/de85e8ef-f49d-4f1a-aabb-4d7b11c68b07)

**Comment by jamesrampton** [comment]
Done.
