### ISSUE TITLE
Ensure people change DJANGO_SECRET_KEY 

### ISSUE THREAD

**Issue by andybak** [icosa-foundation/icosa-gallery#9]
We could give it an invalid or empty value so people *have* to change it.

Or we could seed a random value ourselves somehow? Would have to persist obviously.

**Comment by jamesrampton** [comment]
This is already the case. The secret key is in the `.env` file and is listed in `example.env` as `DJANGO_SECRET_KEY`

**Comment by andybak** [comment]
Cool
